# Your site's title and description. You should change these when you create your own site.
title: Jekyll Solace Theme                  # change me
description: An amazingly light, simple, but functional theme for Jekyll blogs

# Uncomment this line to use the solace theme properly
# remote_theme: samba/jekyll-solace-theme

# Populate the following with actual usernames, or delete them to prevent showing links
author: 
  name: Your Name Here                      # change me
  twitter: (twitter username)               # change me
  linkedin: (linkedin username)             # change me
  github: (github usernme)                  # change me

# Which service should @mentions reference?
jekyll-mentions:
  base_url: https://twitter.com
# alternative:  base_url: https://github.com


# Configuration for navigation behavior
# NB: external links are managed in /_data/navigation.yml
navigation:
  pages_disabled: false                     # disable site's pages in the navigation panel
  hide_blog: false                          # disable site's blog in the navigation panel
  hide_blog_tags: false                     # disable just the blog *tags* in the nav panel
  hide_blog_categories: false               # disable just the blog *categories* in the nav panel
  tag_count: 5                              # how many recent tags to show in the nav panel
  category_count: 5                         # how many recent categories to show in the nav panel


# Configuration for the listing of recent blog posts on home layout. 
# (_layouts/home-blog-sections.html)
home:
  blog:
    enabled: true
    pinned:
      # enabled: true
      # display_mode: excerpt                 # options are "fullbody" or "excerpt". 
    recent:
      # enabled: true
      # display_mode: fullbody                 # options are "fullbody" or "excerpt". 


# Automatically infer title values from page content if needed
# NB: https://github.com/benbalter/jekyll-titles-from-headings
titles_from_headings:
  enabled:     true                         # if pages provide an H1 header, but no page.title, automatically use it
  strip_title: true
  collections: false

# Parse all Markdown files as pages, and interpolate missing frontmatter.
# NOTE: this *may* conflict with readme_index options, when `include` list contains README.md
optional_front_matter:
  enabled:          true                     # disable here if desired
  remove_originals: true

# If the site has a README, generate <index.html> from it.
# NOTE: if the `include` list below includes README.md, this plugin stops working.
readme_index:
  enabled:          true                     # disable here if desired
  remove_originals: true


# Automatically resolve relative links correctly, to the generated output files.
relative_links:
  enabled:     true
  collections: false

# If this site is for a GitHub repository, update this and uncomment it:
# repository: username/repo-name

collections:
  posts:
    title: "Blog"
    layout: post
    menu: false
  hidden:
    layout: page
    menu: false
    hidden: true
    output: true

# How many blog posts would you like to see on your /blog pages?
paginate: 3
paginate_path: /blog/page/:num
permalink: /blog/:year/:categories/:slug

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      hidden: false
      body_class: post
      menu: false
  
  - scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "page"
      hidden: false
      seo_title: null
      menu: false

  - scope:  # this rule prevents blog listing pages from registering in nav menu
      path: "blog"
      type: "pages"
    values:
      hidden: false
      body_class: blog
      menu: false
    
  - scope:
      path: "pages" # pages under the /pages/ directory
      type: "pages"
    values:
      layout: "page"
      hidden: false
      seo_title: null
      menu: true
    
  - scope:
      path: "assets/**/*.pdf"
    values:
      sitemap: false  # do not include them in the sitemap
  
  - scope:
      path: "404.html"
    values:
      menu: false
      hidden: true



markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  tables: true
  autolink: true
  auto_ids: true
  syntax_highlighter: rouge
  parse_block_html: true
  parse_span_html: true


highlighter: rouge

rouge:
  css_class: "codehilite"
  scope: ".codehilite"


plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-relative-links
- jekyll-github-metadata
- jekyll-readme-index
- jekyll-titles-from-headings
- jekyll-optional-front-matter
- jekyll-feed
- jekyll-gist
- jekyll-avatar
- jemoji
- rouge
- kramdown

# include:
# - README.md

exclude:
- CNAME
- Gemfile
- Gemfile.lock
- jekyll-solace-theme.gemspec
- Makefile
- util/*
- DOCKER_ENV*