title: Jekyll Solace Theme
description: An amazingly light, simple, but functional theme for Jekyll blogs

# How many blog posts would you like to see on your /blog pages?
paginate: 3
paginate_path: /blog/page/:num
permalink: /blog/:year/:categories/:slug

# Populate the following with actual usernames, or delete them to prevent showing links
author: 
  name: Your Name Here
  twitter: (twitter username)
  linkedin: (linkedin username)
  github: (github usernme)


# Configuration for navigation behavior
# NB: external links are managed in /_data/navigation.yml
navigation:
  pages_disabled: false
  hide_blog: false
  hide_blog_tags: false
  hide_blog_categories: false
  tag_count: 5
  category_count: 5

collections:
  posts:
    title: "Blog"
    layout: post
    menu: false
  hidden:
    layout: page
    menu: false
    hidden: true
    output: true



defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      hidden: false
      body_class: post
      menu: false
  
  - scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "page"
      hidden: false
      seo_title: null
      menu: false

  - scope:  # this rule prevents blog listing pages from registering in nav menu
      path: "blog"
      type: "pages"
    values:
      hidden: false
      body_class: blog
      menu: false
    
  - scope:
      path: "pages" # pages under the /pages/ directory
      type: "pages"
    values:
      layout: "page"
      hidden: false
      seo_title: null
      menu: true

    
  - scope:
      path: "404.html"
    values:
      menu: false
      hidden: true


markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  tables: true
  autolink: true
  auto_ids: true
  syntax_highlighter: rouge
  parse_block_html: true
  parse_span_html: true


highlighter: rouge

rouge:
  css_class: "codehilite"
  scope: ".codehilite"


plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- rouge
- kramdown

exclude:
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- jekyll-solace-theme.gemspec
- Makefile
- util/*